### PR TITLE
Hot key support with default ctrl + l and cmd + k as clear support

### PR DESCRIPTION
**Pull request by jcgertig**
@nitin42 This adds keyboard shortcuts as #8  wanted. better docs will go into the wiki

### CODE REVIEW

**Comment by nitin42** [comment]
Oh that's great 👍 . I'm a little busy with an other project so if you think it's working properly without any bugs (previous PR disabled the max, min and close 😅 ) then go ahead and merge this 😄

**Comment by nitin42** [comment]
Also document the changes in the `readme`. Thanks!!

**Comment by nitin42** [comment]
If I find some more time, we can think about adding a small web page describing the project! Let me know what you think 😃

**Comment by jcgertig** [comment]
Yep already did also if you have noticed this is a new branch called 3.X.X. Yeah that would be good. Use this as the ui as well

**Comment by jcgertig** [comment]
Yeah I was not paying attention the min, max I actually am adding a way to disable them altogether. I don't want my users to to that.

**Comment by jcgertig** [comment]
Ill go ahead and merge this but I cant release you can add me to the npm as a owner by doing `npm owner add jcgertig` if you want to give me access to release as well.

**Comment by nitin42** [comment]
Cool, I will let you know!

**Comment by nitin42** [comment]
Added !!

**Comment by nitin42** [comment]
Also, If you share this with your friends or on your Twitter (little promotion), I'll be very happy 😄 .

**Pull request merged**
