### PR TITLE
added history feature in the new terminal structure

### PR DESCRIPTION
**Pull request by CVarisco**
I hope that now it is ok 🙂 
Thanks @nitin42 @jcgertig !

### CODE REVIEW

**Comment by nitin42** [comment]
Can you upload a gif ? I want to see the working and then I'll be happy to merge this! Thanks again!

**Comment by CVarisco** [comment]
Sure!
Check it out! 
jul-09-2017 12-54-46

**Comment by nitin42** [comment]
SUPERB!!! Awesome work!

**Comment by nitin42** [comment]
Can you create one more PR ? For documenting this feature. It will great !

**Comment by CVarisco** [comment]
Sure!
If you wait a little bit, I could commit on this PR the documentation 👍

**Comment by nitin42** [comment]
Sure!

**Comment by CVarisco** [comment]
What do you think?

`README.md`
## Built-in functionality
* History of your commands available pressing key up and key down

**Comment by nitin42** [comment]
Thanks for the changes! I'm currently reviewing your PR 😄  and will merge soon! Great job 👍

**Comment by nitin42** [comment]
I think you're still not in sync with the current HEAD. See this - 

You've added `showContent(...)`



But I've already merged @jcgertig PR and if you look carefully there are some changes - 



Same goes for the other parts. There are some conflicts!

**Comment by CVarisco** [comment]
OMG, I'm sorry.
Could I resolve conflicts ?

**Comment by nitin42** [comment]
Yup. If that doesn't work, make a new PR by pulling the new changes first 😄

**Comment by CVarisco** [comment]
Yeah, it's a better idea.
I'm closing this because it's to confusing now...
Thanks and sorry again.

**Comment by nitin42** [comment]
No worries. This also happens to me when I'm contributing elsewhere. Difficult to watch the changes and then make yours. 👍  Go ahead and make a new PR

**Pull request closed without merging**
