### PR TITLE
added history with new terminal code

### PR DESCRIPTION
**Pull request by CVarisco**
I hope that now is ok 🙂 
Thanks @nitin42 !

### CODE REVIEW

**Comment by nitin42** [comment]
Thanks @CVarisco !!

**Comment by nitin42** [comment]
Its awesome!! 👍

**Comment by nitin42** [comment]
@CVarisco I was just wondering if we could add `autocompletion` with tab ? By searching the current list of the commands with the input prefix ? Let me know what you think !

**Comment by CVarisco** [comment]
@nitin42 Cool!
I think that we can do in steps 🌴 
1) `autocomplete` the first result on commands pressing tab. (I can do in this week)
2) List of command that is similar of the part typed and move in the list clicking tab (but this is so complex now).

What do you think ?

**Comment by nitin42** [comment]
Great! If you want to try this, go ahead and let me know if you need any help. I will start exploring more on this in the morning!

**Comment by jcgertig** [comment]
@CVarisco im actually using a library for string similarity [https://www.npmjs.com/package/string-similarity](https://www.npmjs.com/package/string-similarity) it give a percent of similarity can be used for autocomplete

**Comment by CVarisco** [comment]
@jcgertig Thanks man!
I'm working on it, and I need to edit the handler of history.
Because now we have a lot case with keyCode.

Soon I push the `autocomplete` 💪

**Comment by nitin42** [comment]
But are we sure it will give the best match if we use this ?

**Comment by jcgertig** [comment]
it has  `findBestMatch`  @nitin42

**Comment by jcgertig** [comment]
also look into [whatkey](https://www.npmjs.com/package/whatkey) @CVarisco

**Comment by nitin42** [comment]
Ok. I'll look further into this in the morning!

**Comment by CVarisco** [comment]
`findBestMatch(inputValue, Object.keys(commands))` 🙂

**Comment by jcgertig** [comment]
Yep that

**Comment by jcgertig** [comment]
I'm actually using it in the args parsing for advanced commands

**Comment by jcgertig** [comment]
screen shot 2017-07-09 at 3 23 20 pm

**Comment by jcgertig** [comment]
Im requiring at least a 50% or 0.5 certainty before it outputs

**Comment by jcgertig** [comment]
I think in the case of auto complete maybe it its < 50% then list the most likely ones

**Comment by jcgertig** [comment]
like unix does on double tab

**Comment by jcgertig** [comment]
but yeah you said you had issues with keycodes look into [whatkey](https://www.npmjs.com/package/whatkey)

**Comment by CVarisco** [comment]
@jcgertig Ok, the functionality is ok.
But, when you press `tab` the browser detect the tab and change focus.
How we can resolve this ?

**Comment by CVarisco** [comment]
Resolved very easy 🙂  `event.preventDefault();`

**Pull request merged**
