### PR TITLE
Command passthrough

### PR DESCRIPTION
**Pull request by jcgertig**
Allows a user to take over any commands that have not been defined and process them.

@nitin42  also added a houndci config so you can go to [https://houndci.com](https://houndci.com) and have it watch this repo. It will allow the linter to run on every pr

### CODE REVIEW

**Comment by nitin42** [comment]
Thanks again !! Btwn you will need to do `git pull` because I've published V2.0.0. Let me know if you need some help!

**Comment by jcgertig** [comment]
@nitin42 also refactored the close and minimize code. I do want to say that be aware of semver. 2.0.0 was not needed yet there were no breaking changes. It should have just been  minor version release.

**Comment by jcgertig** [comment]
also give me a min I see the clear no longer works

**Comment by nitin42** [comment]
@jcgertig I thought may be it's a new feature so ... next time I'll take care of `major.minor.patch`

**Comment by nitin42** [comment]
Clear command is working on my end 👍

**Comment by nitin42** [comment]
I just started refactoring the hide and show code (because its verbose and I want to keep the bundle size small) and it looks something similar to your code. Great! I will undo my changes and will merge this PR. Thank you!

I will start working on animations and some more interesting stuff then !

**Comment by jcgertig** [comment]
Got it fixed @nitin42

**Comment by nitin42** [comment]
Thanks @jcgertig !!

**Comment by nitin42** [comment]
Btwn @jcgertig can you revert this.

Earlier - 



With new changes - 



Do you see the difference between the prompts in both the gifs ? Can you change it back (to earlier) ? 

Thanks!

**Comment by jcgertig** [comment]
Ill fix this in #12 now

**Comment by nitin42** [comment]
Thank you!

**Comment by nitin42** [comment]
Also if you're interested I was thinking about typography, to make the content look more elegant. Let me know what you think!

**Comment by jcgertig** [comment]
I think a monospace font by default because that more terminalish also fixed the issue

**Comment by nitin42** [comment]
You'll include this in #12  ?

**Pull request merged**
