### PR TITLE
Added Storybook and StyledComponents. Removed Sass

### PR DESCRIPTION
**Pull request by carvallegro**
**Note** : I didn't made any functional or visual changes. The features are still "as-is" because this is a big change. If this PR is accepted I'll add a few more things to the styling to extend the visual customization.

- feat(storybook) : Added [Storybook](https://storybook.js.org) to the project, it will allow to visually test the Terminal component with different cases. Improvement of the starter folder.
- feat(styled-components) : Refactored Terminal to have in-JS styling through HOC. [StyledComponent](https://www.styled-components.com) simplifies the whole thing and allows a dynamic theming. Avoid having to load a CSS file. 
- cleanup(Sass) : Removed Sass files and webpack styled loader as they're unecessary now

### CODE REVIEW

**Comment by carvallegro** [comment]
Don't really know how to fix HoundCI there. If someone has a idea...

**Comment by carvallegro** [comment]
Not really sure how to fix HoundCI here...

If someone has an idea, please suggest !

**Comment by jcgertig** [comment]
you can ignore for now its a issue on houndci side

**Comment by jcgertig** [comment]
please remove anything related to hound

**Comment by carvallegro** [comment]
@jcgertig I just disabled HoundCI. To be put back when they fix the issue

**Comment by jcgertig** [comment]
also revert your hound changes please

**Comment by jcgertig** [comment]
you have not changed the build script please updated it and make sure its still working

**Comment by carvallegro** [comment]
Done

**Comment by jcgertig** [comment]
Please make sure the build script is fine it still has the scss build process in it but you removed node-sccs

**Comment by carvallegro** [comment]
Yups, sorry for that, on it.

I'm also doing a round trip of every scripts and noticed a error with the test concerning the plugin, 
do you have it on your side ?

**Comment by jcgertig** [comment]
The tests are old the plugin system was in flux for a bit

**Comment by carvallegro** [comment]
There's still an exception when I run it though, it's not a test failure. Will look at it later, it's 2am here

**Comment by carvallegro** [comment]
@jcgertig,  @nitin42  I've updated my PR, could you check the plugin thing ? Not sure if it's expected behavior

**Comment by carvallegro** [comment]
@jcgertig @nitin42 tests are now passing, scripts are running

**Comment by jcgertig** [comment]
Sweet will pull this down and check it

**Comment by nitin42** [comment]
SO AWESOME @carvallegro and thanks @jcgertig for reviewing this 😃 ! I'm a little busy with a project. I am working on this right now 👇  (its unrelated but wanted to share)

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Render React Components to word documents <a href="https://twitter.com/hashtag/reactjs?src=hash">#reactjs</a> 😎 <a href="https://t.co/lCYgYBgTPR">pic.twitter.com/lCYgYBgTPR</a></p>&mdash; Nitin Tulswani (@NTulswani) <a href="https://twitter.com/NTulswani/status/895368933783490560">August 9, 2017</a></blockquote>

**Comment by jcgertig** [comment]
The text in side tabs should be centered

**Comment by jcgertig** [comment]
@carvallegro think thats the only issue I can see

**Comment by carvallegro** [comment]
@jcgertig All g now

**Comment by jcgertig** [comment]
Going in to day sorry was busy this week

**Comment by jcgertig** [comment]
Sorry it's taken so long I merged a released 3.5.0 with your changes. I had a few issues that I had to work through with some of my changes.

**Pull request merged**
